project_name: my_flutter_app

# Available options for architecture:
#   - clean_architecture (default)
#   - mvc_architecture
#   - mvvm_architecture
architecture: clean_architecture 

# Available options for features_strategy:
#   - inLib (default) : all features are in the same lib folder
#   - independantModules : for each feature, we will create a flutter module package for domain, data layer. Presentation layer are always in a project root lib folder
# 
# Note: "independantModules" option is only available for clean_architecture
# By default, all features are in the same lib folder (inLib)
features_strategy: inLib

# List of features:
features:
  - authentication:
      name: authentication
      description: Authentication feature
      entity_attributes:
        email: String
        otp: String
        password: String
        token: String
        id: int
      usecases:
        - getUserOtp:
            use_case_type: Future
            description: Retrieve OTP for user authentication
            attributes:
              email: String
        - verifyUserOtp:
            use_case_type: Future
            description: Verify OTP code
            attributes:
              email: String
              otp: String
        - verifyUserExistence:
            use_case_type: Future
            description: Verify user existence

  - user_profile:
      name: user_profile
      description: User profile management
      entity_attributes:
        id: int
        username: String
        profile_picture: String
        bio: String
      usecases:
        - getUserProfile:
            use_case_type: Stream
            description: Retrieve user profile
            attributes:
              id: int
        - updateUserProfile:
            use_case_type: Future
            description: Update user profile details
            attributes:
              id: int
              username: String
              profile_picture: String
              bio: String

  - settings:
      name: settings
      description: Application settings management
      entity_attributes:
        notifications_enabled: bool
        language: String
        theme: String
      usecases:
        - getSettings:
            use_case_type: Future
            description: Retrieve user settings
        - updateSettings:
            use_case_type: Future
            description: Update application settings
            attributes:
              notifications_enabled: bool
              language: String
              theme: String

# State management
# By default, state management is GetX
# - getx, bloc, cubit, provider, riverpod, mobx
# Note : Only none and getx is available for the moment.
state_management: getx

# List of environments:
envs:
  - development
  - staging
  - production

# List of environment variables:
env_variables:
  - ENV1
  - ENV2

macros:
  - name: '%{PROJECT_NAME}%'
    value: my_flutter_app
