name: project_structure_builder
description: "A tool to configure and generate Flutter project structures based on your architectural needs."
version: 0.0.2
homepage: https://github.com/BaHithBENON/flutter_project_structure_builder

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  yaml: ^3.1.3
  args: ^2.6.0
  path: ^1.9.0
  xml: ^6.5.0

  flutter:
    sdk: flutter
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  project_structure_builder: